print('this is a test file')
print('this is the second line from cloud')
print('this is the second line from cloud1')
print('this is the third line from Local')
print('this is the third line from Local1')
